var searchData=
[
  ['name',['name',['http://doc.qt.io/qt-5/qscreen.html#name-prop',0,'QScreen::name()'],['http://doc.qt.io/qt-5/qicon.html#name',0,'QIcon::name()'],['http://doc.qt.io/qt-5/qimageiohandler-obsolete.html#name',0,'QImageIOHandler::name()'],['http://doc.qt.io/qt-5/qscreen.html#name-prop',0,'QScreen::name()'],['http://doc.qt.io/qt-5/qtouchdevice.html#name',0,'QTouchDevice::name()'],['http://doc.qt.io/qt-5/qcolor.html#name',0,'QColor::name() const'],['http://doc.qt.io/qt-5/qcolor.html#name-1',0,'QColor::name(NameFormat format) const'],['http://doc.qt.io/qt-5/qpagesize.html#name',0,'QPageSize::name() const'],['http://doc.qt.io/qt-5/qpagesize.html#name-1',0,'QPageSize::name(PageSizeId pageSizeId)'],['http://doc.qt.io/qt-5/qtextimageformat.html#name',0,'QTextImageFormat::name()'],['http://doc.qt.io/qt-5/qtextcodec.html#name',0,'QTextCodec::name()'],['http://doc.qt.io/qt-5/qstorageinfo.html#name',0,'QStorageInfo::name()'],['http://doc.qt.io/qt-5/qmetamethod.html#name',0,'QMetaMethod::name()'],['http://doc.qt.io/qt-5/qmetaenum.html#name',0,'QMetaEnum::name()'],['http://doc.qt.io/qt-5/qmetaproperty.html#name',0,'QMetaProperty::name()'],['http://doc.qt.io/qt-5/qmetaclassinfo.html#name',0,'QMetaClassInfo::name()'],['http://doc.qt.io/qt-5/qgenericargument.html#name',0,'QGenericArgument::name()'],['http://doc.qt.io/qt-5/qmimetype.html#name',0,'QMimeType::name()'],['http://doc.qt.io/qt-5/qlocale.html#name',0,'QLocale::name()'],['http://doc.qt.io/qt-5/qxmlstreamattribute.html#name',0,'QXmlStreamAttribute::name()'],['http://doc.qt.io/qt-5/qxmlstreamnotationdeclaration.html#name',0,'QXmlStreamNotationDeclaration::name()'],['http://doc.qt.io/qt-5/qxmlstreamentitydeclaration.html#name',0,'QXmlStreamEntityDeclaration::name()'],['http://doc.qt.io/qt-5/qxmlstreamreader.html#name',0,'QXmlStreamReader::name()']]],
  ['namedcapturegroups',['namedCaptureGroups',['http://doc.qt.io/qt-5/qregularexpression.html#namedCaptureGroups',0,'QRegularExpression']]],
  ['namefilterdetailsvisible',['nameFilterDetailsVisible',['http://doc.qt.io/qt-5/qfiledialog-obsolete.html#nameFilterDetailsVisible-prop',0,'QFileDialog']]],
  ['namefilterdisables',['nameFilterDisables',['http://doc.qt.io/qt-5/qfilesystemmodel.html#nameFilterDisables-prop',0,'QFileSystemModel::nameFilterDisables()'],['http://doc.qt.io/qt-5/qfilesystemmodel.html#nameFilterDisables-prop',0,'QFileSystemModel::nameFilterDisables() const']]],
  ['namefilters',['nameFilters',['http://doc.qt.io/qt-5/qfiledialog.html#nameFilters',0,'QFileDialog::nameFilters()'],['http://doc.qt.io/qt-5/qfilesystemmodel.html#nameFilters',0,'QFileSystemModel::nameFilters()'],['http://doc.qt.io/qt-5/qdirmodel.html#nameFilters',0,'QDirModel::nameFilters()'],['http://doc.qt.io/qt-5/qdir.html#nameFilters',0,'QDir::nameFilters()']]],
  ['names',['names',['http://doc.qt.io/qt-5/qcommandlineoption.html#names',0,'QCommandLineOption']]],
  ['namespacedeclarations',['namespaceDeclarations',['http://doc.qt.io/qt-5/qxmlstreamreader.html#namespaceDeclarations',0,'QXmlStreamReader']]],
  ['namespaceprocessing',['namespaceProcessing',['http://doc.qt.io/qt-5/qxmlstreamreader.html#namespaceProcessing-prop',0,'QXmlStreamReader::namespaceProcessing()'],['http://doc.qt.io/qt-5/qxmlstreamreader.html#namespaceProcessing-prop',0,'QXmlStreamReader::namespaceProcessing() const']]],
  ['namespaceuri',['namespaceUri',['http://doc.qt.io/qt-5/qxmlstreamattribute.html#namespaceUri',0,'QXmlStreamAttribute::namespaceUri()'],['http://doc.qt.io/qt-5/qxmlstreamnamespacedeclaration.html#namespaceUri',0,'QXmlStreamNamespaceDeclaration::namespaceUri()'],['http://doc.qt.io/qt-5/qxmlstreamreader.html#namespaceUri',0,'QXmlStreamReader::namespaceUri()']]],
  ['nametotype',['nameToType',['http://doc.qt.io/qt-5/qvariant.html#nameToType',0,'QVariant']]],
  ['nativearguments',['nativeArguments',['http://doc.qt.io/qt-5/qprocess.html#nativeArguments',0,'QProcess']]],
  ['nativecountryname',['nativeCountryName',['http://doc.qt.io/qt-5/qlocale.html#nativeCountryName',0,'QLocale']]],
  ['nativeevent',['nativeEvent',['http://doc.qt.io/qt-5/qwizard.html#nativeEvent',0,'QWizard::nativeEvent()'],['http://doc.qt.io/qt-5/qwidget.html#nativeEvent',0,'QWidget::nativeEvent()'],['http://doc.qt.io/qt-5/qwindow.html#nativeEvent',0,'QWindow::nativeEvent()']]],
  ['nativeeventfilter',['nativeEventFilter',['http://doc.qt.io/qt-5/qabstractnativeeventfilter.html#nativeEventFilter',0,'QAbstractNativeEventFilter']]],
  ['nativehandle',['nativeHandle',['http://doc.qt.io/qt-5/qopenglcontext.html#nativeHandle',0,'QOpenGLContext']]],
  ['nativekey',['nativeKey',['http://doc.qt.io/qt-5/qsharedmemory.html#nativeKey',0,'QSharedMemory']]],
  ['nativelanguagename',['nativeLanguageName',['http://doc.qt.io/qt-5/qlocale.html#nativeLanguageName',0,'QLocale']]],
  ['nativemenubar',['nativeMenuBar',['http://doc.qt.io/qt-5/qmenubar.html#nativeMenuBar-prop',0,'QMenuBar']]],
  ['nativemodifiers',['nativeModifiers',['http://doc.qt.io/qt-5/qkeyevent.html#nativeModifiers',0,'QKeyEvent']]],
  ['nativeorientation',['nativeOrientation',['http://doc.qt.io/qt-5/qscreen.html#nativeOrientation-prop',0,'QScreen::nativeOrientation()'],['http://doc.qt.io/qt-5/qscreen.html#nativeOrientation-prop',0,'QScreen::nativeOrientation() const']]],
  ['nativeparentwidget',['nativeParentWidget',['http://doc.qt.io/qt-5/qwidget.html#nativeParentWidget',0,'QWidget']]],
  ['nativescancode',['nativeScanCode',['http://doc.qt.io/qt-5/qkeyevent.html#nativeScanCode',0,'QKeyEvent']]],
  ['nativeview',['nativeView',['http://doc.qt.io/qt-5/qmacnativewidget.html#nativeView',0,'QMacNativeWidget']]],
  ['nativevirtualkey',['nativeVirtualKey',['http://doc.qt.io/qt-5/qkeyevent.html#nativeVirtualKey',0,'QKeyEvent']]],
  ['naturaltextrect',['naturalTextRect',['http://doc.qt.io/qt-5/qtextline.html#naturalTextRect',0,'QTextLine']]],
  ['naturaltextwidth',['naturalTextWidth',['http://doc.qt.io/qt-5/qtextline.html#naturalTextWidth',0,'QTextLine']]],
  ['navigationbarvisible',['navigationBarVisible',['http://doc.qt.io/qt-5/qcalendarwidget.html#navigationBarVisible-prop',0,'QCalendarWidget']]],
  ['navigationcheckbox',['navigationCheckBox',['../class_m_calendar_page.html#ae8345bf9dffc54a886976fa46b1bd730',1,'MCalendarPage']]],
  ['navigationlabel',['navigationLabel',['../class_m_calendar_page.html#a3461a236433777dd99e290abd428d188',1,'MCalendarPage']]],
  ['navigationmode',['navigationMode',['http://doc.qt.io/qt-5/qapplication.html#navigationMode',0,'QApplication']]],
  ['negativesign',['negativeSign',['http://doc.qt.io/qt-5/qlocale.html#negativeSign',0,'QLocale']]],
  ['newinstance',['newInstance',['http://doc.qt.io/qt-5/qmetaobject.html#newInstance',0,'QMetaObject']]],
  ['newpage',['newPage',['http://doc.qt.io/qt-5/qpagedpaintdevice.html#newPage',0,'QPagedPaintDevice::newPage()'],['http://doc.qt.io/qt-5/qpdfwriter.html#newPage',0,'QPdfWriter::newPage()']]],
  ['newpos',['newPos',['http://doc.qt.io/qt-5/qgraphicsscenemoveevent.html#newPos',0,'QGraphicsSceneMoveEvent']]],
  ['newproxywidget',['newProxyWidget',['http://doc.qt.io/qt-5/qgraphicsproxywidget.html#newProxyWidget',0,'QGraphicsProxyWidget']]],
  ['newsize',['newSize',['http://doc.qt.io/qt-5/qgraphicssceneresizeevent.html#newSize',0,'QGraphicsSceneResizeEvent']]],
  ['next',['next',['http://doc.qt.io/qt-5/qwizard.html#next',0,'QWizard::next()'],['http://doc.qt.io/qt-5/qtextblock.html#next',0,'QTextBlock::next()'],['http://doc.qt.io/qt-5/qdiriterator.html#next',0,'QDirIterator::next()'],['http://doc.qt.io/qt-5/qregularexpressionmatchiterator.html#next',0,'QRegularExpressionMatchIterator::next()'],['http://doc.qt.io/qt-5/qmutablesetiterator.html#next',0,'QMutableSetIterator::next()'],['http://doc.qt.io/qt-5/qfutureiterator.html#next',0,'QFutureIterator::next()'],['http://doc.qt.io/qt-5/qlinkedlistiterator.html#next',0,'QLinkedListIterator::next()'],['http://doc.qt.io/qt-5/qlistiterator.html#next',0,'QListIterator::next()'],['http://doc.qt.io/qt-5/qsetiterator.html#next',0,'QSetIterator::next()'],['http://doc.qt.io/qt-5/qvectoriterator.html#next',0,'QVectorIterator::next()'],['http://doc.qt.io/qt-5/qmutablelinkedlistiterator.html#next',0,'QMutableLinkedListIterator::next()'],['http://doc.qt.io/qt-5/qmutablelistiterator.html#next',0,'QMutableListIterator::next()'],['http://doc.qt.io/qt-5/qmutablevectoriterator.html#next',0,'QMutableVectorIterator::next()'],['http://doc.qt.io/qt-5/qhashiterator.html#next',0,'QHashIterator::next()'],['http://doc.qt.io/qt-5/qmapiterator.html#next',0,'QMapIterator::next()'],['http://doc.qt.io/qt-5/qmutablehashiterator.html#next',0,'QMutableHashIterator::next()'],['http://doc.qt.io/qt-5/qmutablemapiterator.html#next',0,'QMutableMapIterator::next()']]],
  ['nextcheckstate',['nextCheckState',['http://doc.qt.io/qt-5/qabstractbutton.html#nextCheckState',0,'QAbstractButton::nextCheckState()'],['http://doc.qt.io/qt-5/qcheckbox.html#nextCheckState',0,'QCheckBox::nextCheckState()'],['http://doc.qt.io/qt-5/qtoolbutton.html#nextCheckState',0,'QToolButton::nextCheckState()']]],
  ['nextcursorposition',['nextCursorPosition',['http://doc.qt.io/qt-5/qtextlayout.html#nextCursorPosition',0,'QTextLayout']]],
  ['nextframedelay',['nextFrameDelay',['http://doc.qt.io/qt-5/qmovie.html#nextFrameDelay',0,'QMovie']]],
  ['nextid',['nextId',['http://doc.qt.io/qt-5/qwizard.html#nextId',0,'QWizard::nextId()'],['http://doc.qt.io/qt-5/qwizardpage.html#nextId',0,'QWizardPage::nextId()']]],
  ['nextimagedelay',['nextImageDelay',['http://doc.qt.io/qt-5/qimageiohandler.html#nextImageDelay',0,'QImageIOHandler::nextImageDelay()'],['http://doc.qt.io/qt-5/qimagereader.html#nextImageDelay',0,'QImageReader::nextImageDelay()']]],
  ['nextinfocuschain',['nextInFocusChain',['http://doc.qt.io/qt-5/qwidget.html#nextInFocusChain',0,'QWidget']]],
  ['nextpageaction',['nextPageAction',['http://doc.qt.io/qt-5/qaccessibleactioninterface.html#nextPageAction',0,'QAccessibleActionInterface']]],
  ['nexttransition',['nextTransition',['http://doc.qt.io/qt-5/qtimezone.html#nextTransition',0,'QTimeZone']]],
  ['nlerp',['nlerp',['http://doc.qt.io/qt-5/qquaternion.html#nlerp',0,'QQuaternion']]],
  ['nonbreakablelines',['nonBreakableLines',['http://doc.qt.io/qt-5/qtextblockformat.html#nonBreakableLines',0,'QTextBlockFormat']]],
  ['noquote',['noquote',['http://doc.qt.io/qt-5/qdebug.html#noquote',0,'QDebug']]],
  ['normal',['normal',['http://doc.qt.io/qt-5/qvector3d.html#normal',0,'QVector3D::normal(const QVector3D &amp;v1, const QVector3D &amp;v2)'],['http://doc.qt.io/qt-5/qvector3d.html#normal-1',0,'QVector3D::normal(const QVector3D &amp;v1, const QVector3D &amp;v2, const QVector3D &amp;v3)']]],
  ['normalgeometry',['normalGeometry',['http://doc.qt.io/qt-5/qwidget.html#normalGeometry-prop',0,'QWidget::normalGeometry()'],['http://doc.qt.io/qt-5/qwidget.html#normalGeometry-prop',0,'QWidget::normalGeometry() const']]],
  ['normalize',['normalize',['http://doc.qt.io/qt-5/qquaternion.html#normalize',0,'QQuaternion::normalize()'],['http://doc.qt.io/qt-5/qvector2d.html#normalize',0,'QVector2D::normalize()'],['http://doc.qt.io/qt-5/qvector3d.html#normalize',0,'QVector3D::normalize()'],['http://doc.qt.io/qt-5/qvector4d.html#normalize',0,'QVector4D::normalize()']]],
  ['normalized',['normalized',['http://doc.qt.io/qt-5/qquaternion.html#normalized',0,'QQuaternion::normalized()'],['http://doc.qt.io/qt-5/qvector2d.html#normalized',0,'QVector2D::normalized()'],['http://doc.qt.io/qt-5/qvector3d.html#normalized',0,'QVector3D::normalized()'],['http://doc.qt.io/qt-5/qvector4d.html#normalized',0,'QVector4D::normalized()'],['http://doc.qt.io/qt-5/qrect.html#normalized',0,'QRect::normalized()'],['http://doc.qt.io/qt-5/qrectf.html#normalized',0,'QRectF::normalized()'],['http://doc.qt.io/qt-5/qstring.html#normalized',0,'QString::normalized()'],['http://doc.qt.io/qt-5/qversionnumber.html#normalized',0,'QVersionNumber::normalized()']]],
  ['normalizedpos',['normalizedPos',['http://doc.qt.io/qt-5/qtouchevent-touchpoint.html#normalizedPos',0,'QTouchEvent::TouchPoint']]],
  ['normalizedsignature',['normalizedSignature',['http://doc.qt.io/qt-5/qmetaobject.html#normalizedSignature',0,'QMetaObject']]],
  ['normalizedtype',['normalizedType',['http://doc.qt.io/qt-5/qmetaobject.html#normalizedType',0,'QMetaObject']]],
  ['normalizeindexes',['normalizeIndexes',['http://doc.qt.io/qt-5/qcontiguouscache.html#normalizeIndexes',0,'QContiguousCache']]],
  ['normalmatrix',['normalMatrix',['http://doc.qt.io/qt-5/qmatrix4x4.html#normalMatrix',0,'QMatrix4x4']]],
  ['normalvector',['normalVector',['http://doc.qt.io/qt-5/qlinef.html#normalVector',0,'QLineF']]],
  ['nospace',['nospace',['http://doc.qt.io/qt-5/qdebug.html#nospace',0,'QDebug']]],
  ['notation',['notation',['http://doc.qt.io/qt-5/qdoublevalidator.html#notation-prop',0,'QDoubleValidator::notation()'],['http://doc.qt.io/qt-5/qdoublevalidator.html#notation-prop',0,'QDoubleValidator::notation() const']]],
  ['notationdeclarations',['notationDeclarations',['http://doc.qt.io/qt-5/qxmlstreamreader.html#notationDeclarations',0,'QXmlStreamReader']]],
  ['notationname',['notationName',['http://doc.qt.io/qt-5/qxmlstreamentitydeclaration.html#notationName',0,'QXmlStreamEntityDeclaration']]],
  ['notchesvisible',['notchesVisible',['http://doc.qt.io/qt-5/qdial.html#notchesVisible-prop',0,'QDial::notchesVisible()'],['http://doc.qt.io/qt-5/qdial.html#notchesVisible-prop',0,'QDial::notchesVisible() const']]],
  ['notchsize',['notchSize',['http://doc.qt.io/qt-5/qdial.html#notchSize-prop',0,'QDial::notchSize()'],['http://doc.qt.io/qt-5/qdial.html#notchSize-prop',0,'QDial::notchSize() const']]],
  ['notchtarget',['notchTarget',['http://doc.qt.io/qt-5/qdial.html#notchTarget-prop',0,'QDial::notchTarget()'],['http://doc.qt.io/qt-5/qdial.html#notchTarget-prop',0,'QDial::notchTarget() const']]],
  ['notify',['notify',['http://doc.qt.io/qt-5/qapplication.html#notify',0,'QApplication::notify()'],['http://doc.qt.io/qt-5/qguiapplication.html#notify',0,'QGuiApplication::notify()'],['http://doc.qt.io/qt-5/qcoreapplication.html#notify',0,'QCoreApplication::notify()']]],
  ['notifysignal',['notifySignal',['http://doc.qt.io/qt-5/qmetaproperty.html#notifySignal',0,'QMetaProperty']]],
  ['notifysignalindex',['notifySignalIndex',['http://doc.qt.io/qt-5/qmetaproperty.html#notifySignalIndex',0,'QMetaProperty']]],
  ['nsecselapsed',['nsecsElapsed',['http://doc.qt.io/qt-5/qelapsedtimer.html#nsecsElapsed',0,'QElapsedTimer']]],
  ['null',['Null',['http://doc.qt.io/qt-5/qstring-null.html',0,'QString']]],
  ['nulldevice',['nullDevice',['http://doc.qt.io/qt-5/qprocess.html#nullDevice',0,'QProcess']]],
  ['number',['number',['http://doc.qt.io/qt-5/qbytearray.html#number',0,'QByteArray::number(int n, int base)'],['http://doc.qt.io/qt-5/qbytearray.html#number-1',0,'QByteArray::number(uint n, int base)'],['http://doc.qt.io/qt-5/qbytearray.html#number-2',0,'QByteArray::number(qlonglong n, int base)'],['http://doc.qt.io/qt-5/qbytearray.html#number-3',0,'QByteArray::number(qulonglong n, int base)'],['http://doc.qt.io/qt-5/qbytearray.html#number-4',0,'QByteArray::number(double n, char f, int prec)'],['http://doc.qt.io/qt-5/qstring.html#number-2',0,'QString::number(int n, int base)'],['http://doc.qt.io/qt-5/qstring.html#number-1',0,'QString::number(uint n, int base)'],['http://doc.qt.io/qt-5/qstring.html#number',0,'QString::number(long n, int base)'],['http://doc.qt.io/qt-5/qstring.html#number-3',0,'QString::number(ulong n, int base)'],['http://doc.qt.io/qt-5/qstring.html#number-4',0,'QString::number(qlonglong n, int base)'],['http://doc.qt.io/qt-5/qstring.html#number-5',0,'QString::number(qulonglong n, int base)'],['http://doc.qt.io/qt-5/qstring.html#number-6',0,'QString::number(double n, char format, int precision)']]],
  ['numbercolor',['numberColor',['../class_analog_clock.html#a1b5736592444a5506fb7324fcdbc9aac',1,'AnalogClock']]],
  ['numberflags',['NumberFlags',['http://doc.qt.io/qt-5/qtextstream.html#NumberFlag-enum',0,'QTextStream::NumberFlags()'],['http://doc.qt.io/qt-5/qtextstream.html#numberFlags',0,'QTextStream::numberFlags() const']]],
  ['numberfont',['numberFont',['../class_analog_clock.html#a4f4799a60c201ac2defe5be7b7eda1f7',1,'AnalogClock']]],
  ['numberfontcombo',['numberFontCombo',['../class_m_clock_page.html#a1601d8aab70b6b73895a0a611016796d',1,'MClockPage']]],
  ['numberfontlabel',['numberFontLabel',['../class_m_clock_page.html#a13a91d5d67a8d399143b3f1aff50ea36',1,'MClockPage']]],
  ['numberoptions',['numberOptions',['http://doc.qt.io/qt-5/qlocale.html#numberOptions',0,'QLocale::numberOptions() const'],['http://doc.qt.io/qt-5/qlocale.html#NumberOption-enum',0,'QLocale::NumberOptions()']]],
  ['numberprefix',['numberPrefix',['http://doc.qt.io/qt-5/qtextlistformat.html#numberPrefix',0,'QTextListFormat']]],
  ['numbers',['numbers',['../class_analog_clock.html#a10ec04e8a21b9daf0cf313be625d9fbb',1,'AnalogClock']]],
  ['numberscheck',['numbersCheck',['../class_m_clock_page.html#ac97481cdbff4e82a86eb8e70dd31899b',1,'MClockPage']]],
  ['numberscolorfield',['numbersColorField',['../class_m_clock_page.html#a085529d10bc05383e4cca547c19dbbde',1,'MClockPage']]],
  ['numberscolorlabel',['numbersColorLabel',['../class_m_clock_page.html#a40763a247a9e939352f13ad410594157',1,'MClockPage']]],
  ['numberslabel',['numbersLabel',['../class_m_clock_page.html#a8642b04b7439f8fca2b170ddbf96bc48',1,'MClockPage']]],
  ['numbersuffix',['numberSuffix',['http://doc.qt.io/qt-5/qtextlistformat.html#numberSuffix',0,'QTextListFormat']]],
  ['numbytes',['numBytes',['http://doc.qt.io/qt-5/qimage-obsolete.html#numBytes',0,'QImage']]],
  ['numcolors',['numColors',['http://doc.qt.io/qt-5/qimage-obsolete.html#numColors',0,'QImage']]],
  ['numericmode',['numericMode',['http://doc.qt.io/qt-5/qcollator.html#numericMode',0,'QCollator']]],
  ['numscreens',['numScreens',['http://doc.qt.io/qt-5/qdesktopwidget-obsolete.html#numScreens',0,'QDesktopWidget']]]
];
