var searchData=
[
  ['readonly',['readOnly',['http://doc.qt.io/qt-5/qfiledialog-obsolete.html#readOnly-prop',0,'QFileDialog::readOnly()'],['http://doc.qt.io/qt-5/qfilesystemmodel.html#readOnly-prop',0,'QFileSystemModel::readOnly()'],['http://doc.qt.io/qt-5/qdirmodel.html#readOnly-prop',0,'QDirModel::readOnly()'],['http://doc.qt.io/qt-5/qabstractspinbox.html#readOnly-prop',0,'QAbstractSpinBox::readOnly()'],['http://doc.qt.io/qt-5/qlineedit.html#readOnly-prop',0,'QLineEdit::readOnly()'],['http://doc.qt.io/qt-5/qplaintextedit.html#readOnly-prop',0,'QPlainTextEdit::readOnly()'],['http://doc.qt.io/qt-5/qtextbrowser.html#readOnly-prop',0,'QTextBrowser::readOnly()'],['http://doc.qt.io/qt-5/qtextedit.html#readOnly-prop',0,'QTextEdit::readOnly()']]],
  ['rect',['rect',['http://doc.qt.io/qt-5/qwidget.html#rect-prop',0,'QWidget']]],
  ['redoavailable',['redoAvailable',['http://doc.qt.io/qt-5/qlineedit.html#redoAvailable-prop',0,'QLineEdit']]],
  ['refreshrate',['refreshRate',['http://doc.qt.io/qt-5/qscreen.html#refreshRate-prop',0,'QScreen']]],
  ['regexp',['regExp',['http://doc.qt.io/qt-5/qregexpvalidator.html#regExp-prop',0,'QRegExpValidator']]],
  ['regularexpression',['regularExpression',['http://doc.qt.io/qt-5/qregularexpressionvalidator.html#regularExpression-prop',0,'QRegularExpressionValidator']]],
  ['remainingtime',['remainingTime',['http://doc.qt.io/qt-5/qtimer.html#remainingTime-prop',0,'QTimer']]],
  ['renderhints',['renderHints',['http://doc.qt.io/qt-5/qgraphicsview.html#renderHints-prop',0,'QGraphicsView']]],
  ['resizeanchor',['resizeAnchor',['http://doc.qt.io/qt-5/qgraphicsview.html#resizeAnchor-prop',0,'QGraphicsView']]],
  ['resizegripsvisible',['resizeGripsVisible',['http://doc.qt.io/qt-5/qcolumnview.html#resizeGripsVisible-prop',0,'QColumnView']]],
  ['resizemode',['resizeMode',['http://doc.qt.io/qt-5/qlistview.html#resizeMode-prop',0,'QListView']]],
  ['resolvesymlinks',['resolveSymlinks',['http://doc.qt.io/qt-5/qfiledialog-obsolete.html#resolveSymlinks-prop',0,'QFileDialog::resolveSymlinks()'],['http://doc.qt.io/qt-5/qfilesystemmodel.html#resolveSymlinks-prop',0,'QFileSystemModel::resolveSymlinks()'],['http://doc.qt.io/qt-5/qdirmodel.html#resolveSymlinks-prop',0,'QDirModel::resolveSymlinks()']]],
  ['rootisdecorated',['rootIsDecorated',['http://doc.qt.io/qt-5/qtreeview.html#rootIsDecorated-prop',0,'QTreeView']]],
  ['rotation',['rotation',['http://doc.qt.io/qt-5/qgraphicsobject.html#rotation-prop',0,'QGraphicsObject']]],
  ['rotationangle',['rotationAngle',['http://doc.qt.io/qt-5/qpinchgesture.html#rotationAngle-prop',0,'QPinchGesture']]],
  ['rowcount',['rowCount',['http://doc.qt.io/qt-5/qtablewidget.html#rowCount-prop',0,'QTableWidget']]],
  ['rowwrappolicy',['rowWrapPolicy',['http://doc.qt.io/qt-5/qformlayout.html#rowWrapPolicy-prop',0,'QFormLayout']]],
  ['rubberbandselectionmode',['rubberBandSelectionMode',['http://doc.qt.io/qt-5/qgraphicsview.html#rubberBandSelectionMode-prop',0,'QGraphicsView']]],
  ['running',['running',['http://doc.qt.io/qt-5/qstatemachine.html#running-prop',0,'QStateMachine']]]
];
